import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import Slidebar from '../Components/Slidebar'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Zalo__clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Slidebar/>
    </div>
  )
}

export default Home
